create table person
(
    person_id integer generated by default as identity
        primary key,
    username  varchar(100) not null,
    password  varchar      not null,
    role      varchar(100) not null
);

create table collection
(
    collection_id integer generated by default as identity
        constraint collections_pkey
            primary key,
    title         varchar(50) not null,
    person_id     integer
        constraint collections_person_id_fkey
            references person
            on delete cascade
);

create table tile
(
    tile_id       integer generated by default as identity
        constraint tiles_pkey
            primary key,
    title         varchar(100) not null,
    description   varchar(500),
    url           varchar(200) not null,
    collection_id integer
        constraint fk_tiles_collections
            references collection
            on delete cascade
);
